### ISSUE TITLE
Could you please upload the supplemental material?

### ISSUE THREAD

**Issue by HuiZeng** [hejingwenhejingwen/AdaFM#2]
Hi, you have done a great job!
Could you please share the supplemental material?
It is highly apprepriated if you can also share the PSNR distances of Modulation Testing (Sec. 4.3) on denoising and super resolution tasks. The performances look really good on the DeJEPG task.

**Comment by hejingwenhejingwen** [comment]
Hi,
http://openaccess.thecvf.com/content_CVPR_2019/supplemental/He_Modulating_Image_Restoration_CVPR_2019_supplemental.pdf
Thanks very much!
Best Regard
Jingwen He

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Hui Zeng <notifications@github.com>
发送时间: 星期日, 七月 7, 2019 7:30 下午
收件人: hejingwenhejingwen/AdaFM
抄送: Subscribed
主题: [hejingwenhejingwen/AdaFM] Could you please upload the supplemental material? (#2)


Hi, you have done a great job!
Could you please share the supplemental material?
It is highly apprepriated if you can also share the PSNR distances of Modulation Testing (Sec. 4.3) on denoising and super resolution tasks. The performances look really good on the DeJEPG task.

―

**Comment by HuiZeng** [comment]
Thanks for your reply!
Best Regard.
