### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by huilinLiu** [hejingwenhejingwen/AdaFM#8]
There are some problem on the subtraction of two images. how can I avoid it？
mse = np.mean((img1 - img2)**2)
ValueError: operands could not be broadcast together with shapes (330,502,3) (1348,2032,3)
It's basically in this position: "util.py", line 111

**Comment by hejingwenhejingwen** [comment]
The input image and the GT image should have the same size. If you are dealing with super resolution, please use bicubic interpretation to scale the input images before training.
Thanks.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: huilinLiu <notifications@github.com>
发送时间: Tuesday, March 31, 2020 7:06:07 PM
收件人: hejingwenhejingwen/AdaFM <AdaFM@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [hejingwenhejingwen/AdaFM] ValueError: operands could not be broadcast together with shapes (#8)


There are some problem on the subtraction of two images. how can I avoid it？
mse = np.mean((img1 - img2)**2)
ValueError: operands could not be broadcast together with shapes (330,502,3) (1348,2032,3)
It's basically in this position: "util.py", line 111

―
